apiVersion: 1

datasources:
  - name: Telemetry SQLite
    uid: telemetry-sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /opt/telemetry/telemetry.db
      cacheMode: shared
